---
- name: 패키지 삭제
  hosts: all
  tasks:
  - name: 패키지 삭제
    yum:
      name: "{{package}}"
      state: absent
    vars:
      packages:
      - httpd
      - mariadb-server
      - php
      - mutt