---
# Web Server Configuration
# *1) Install packages
	# yum -y install httpd mod_ssl
# *2) Web server settings
	# scp files/index.html asible#:/var/www/html/index.html
# *3) Web service startup 
	# systemctl enable --now httpd
# *4) Firewall registration
	# firewall-cmd --permanent --add-service={http,https}
# * 5) SELinux(?)

- name: Install and start Apache HTTPD
  hosts: webservers
  tasks:
    - name: Install and start Apache httpd
    hosts: webservers
    tasks:
      - name : Install packages
        yum:
          name:
            - httpd
            - mod_ssl
          state: present
      - name: Web server settings
        copy:
          src: files/index.html
          dest: /var/www/html/index.html
      - name: Web service startup
        services;
          name: httpd
          state: started
          enabled: yes

      - name: Firewall registration
        firewalld:
          service: http
          permanent: true
          immediate: true
          state: enabled
      
      - name: Firewall registration -https
        firewalld:
          service: https
          permanent: true
          immediate: true
          state: enabled


          
      
      

