---
- name: Task Failure Exercise
  hosts: all
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_service: mariadb
  tasks:
  - name: Stop {{ db_service }} service
    service:
      name: "{{ db_service}}"
      state: stopped

  - name: UnInstall {{ web_package }} package
    yum:
      name: "{{ web_package }}"
      state: absent


  - name: UnInstall {{ db_package }} package
    yum:
      name: "{{ db_package }}"
      state: absent

