- name: DB패키지 설치
  hosts: database_dev
  tasks:
  - name: 패키지 설치
    # yum -y install mariadb-server
    # yum -y install python3-PyMySQL
    # yum
    #   name: "{{ item }}"
    #   state: latest
    # loop: "{{ pkg_db }}"
    # vars:
    #   pkg_db:
    #   - mariadb-server
    #   - python3-PyMySQL

# yum -y install maraiadb-server python3-PyMySQL
    yum:
      name: "{{ pkg_db }}"
      state: latest
    vars:
      pkg_db:
      - mariadb-server
      - python3-PyMySQL
   # when: ansible_distribution == 'CentOS'
    when: ansible_distribution == 'RadHat'
  - name: 서비스 기동
    service:
      name: mariadb
      state: started
      enabled: yes